info:
    app:
        description: Spring Boot Actuator description info
        name: Spring Boot Mastery Course
        version: 1.0.0
    company:
        name: '"Testing @Value"'
management:
    endpoint:
        health:
            show-components: always
            show-details: always
    endpoints:
        web:
            exposure:
                include: health,info,prometheus
server:
    error:
        include-binding-errors: always
        include-message: always
        include-stacktrace: on_param
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:testdb
        username: sa
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: none
        show-sql: true
    main:
        banner-mode: 'off'
